### ISSUE TITLE
spThin fails if input csv does not have default column names

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/shinyENM#1]
The default column names are "SPEC", "LAT", "LONG", but if there are any deviations in the input csv, then spThin balks.

**Comment by mlammens** [comment]
Actually, it's not quite that simple. The file has to have the same names as what ever is set in the `runThin` call in `server.R`

**Comment by ndimhypervol** [comment]
Yeah, if you set the parameters in spThin to the right column names, it works, right? I made sure to set them to "lat", "lon", and "spname" in my branch, but not sure if the SWD version keeps the species name column in values$df or not.

**Comment by Tai-Rocha** [comment]
How can I see the input cvs example of this package ?
Tnks!
