### ISSUE TITLE
remove button

### ISSUE THREAD

**Issue by BrunoVilela** [ndimhypervol/shinyENM#12]
Hey guys, just added a button called remove. It actually remove the points you want by saying the number, but I still can't make the map upload instantly without removing the "isolate" from the map and from the table. If I do this I got the same error while writing the name of the species it uploads the map. I am not sure what could solve this. Do you have any idea?
I am also advancing on let the user click on the map and get the record deleted...

**Comment by ndimhypervol** [comment]
Fixed this by giving both map and tbl a double dependency on both goName and remove buttons.
