### ISSUE TITLE
get more than 50 occurrences from GBIF

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/shinyENM#2]
Seems like we're limited to the first 50 occurrences from a gbif search right now. We'll have to figure out how to move past that.

**Comment by ndimhypervol** [comment]
You can change the limit in the rgbif call by tweaking one of the parameters.

**Comment by BrunoVilela** [comment]
Why not let the user download the amount of occurrence they want by using a slider bar that goes from 1 to 500?

**Comment by BrunoVilela** [comment]
Done...
