### ISSUE TITLE
Should we consider allowing the user to skip spThin?

### ISSUE THREAD

**Issue by mlammens** [ndimhypervol/shinyENM#3]
I think so. Perhaps make spThin a check box, rather than an activate button.

**Comment by ndimhypervol** [comment]
The user can currently skip it, in that it's not essential to run it before ENMeval, but we can make that clear with some text. There's significant prettying up to do on the interface side, and that includes lots of explanatory text and some dividers. Making spThin a checkbox might detract from highlighting it, which is one of the main purposes of this submission: highlight our awesome R packages!
