### ISSUE TITLE
very new version in master

### ISSUE THREAD

**Issue by ndimhypervol** [ndimhypervol/shinyENM#4]
Hey Matt, just merged my branch to master with a very new version that <i>radically</i> redefines the layout. Check it out. Let's work from this, as I tried to implement most of the design changes Rob told me he wanted yesterday. I'm trying not to worry that much about code efficiency, but if you see a big chunk that can be pared down considerably, please go for it. We still need to add plotting for ENMeval (still haven't gotten the code from Bob), and raster plotting. Perhaps this can go in another tab?

**Comment by mlammens** [comment]
Yeah, raster plotting in a separate tab would be cool. I'll open it as a separate issue and close this one.
