### ISSUE TITLE
two errors: <Error in plotMap(values$gbifoccs) : object 'mapWorld' not found> & <Error in x[[1]] : subscript out of bounds>

### ISSUE THREAD

**Issue by bobmuscarella** [ndimhypervol/shinyENM#5]
Hi -
Just tried the new master and it looks cool but the map does not show up.  I also get an error when trying to run ENMeval.  Sorry, I'm not sure how best to report this stuff, let me know if there is a better way.

**Comment by BrunoVilela** [comment]
Hi Bob, you have to remove the # before the mapWorld creation in the plotMap function inside the server script.
We have to change it the master branch...

**Comment by BrunoVilela** [comment]
Also I would remove the numbers from the plot and put the border colors of the points different from their inside color, to better visualize the overlapping points.
I propose that we do not remove the points from the plot after the thinning process, but instead mark them with another color. So the user can know exactly what they have removed or maybe a checkbox were the user could mark to see the excluded points or not (I like more the checkbox).

**Comment by BrunoVilela** [comment]
the map could be adapted to the buffer, increase when the buffer increase. Sometimes it disappear.

**Comment by ndimhypervol** [comment]
Not sure why you are having these issues, because what's on master works fine on my end. The map loads, the polygon updates dynamically on the map when the buffer is changed, etc. But this testing is essential because it should work the same on everyone's computer.

**Comment by BrunoVilela** [comment]
Hey Jamie, try to clean your environment and try again, maybe the object is save in your computer.
I solve this here by removing the # before the mapWorld creation in the plotMap function inside the server script.

**Comment by bobmuscarella** [comment]
Removing # from the following two lines fixed the problem for me, too:
     mapWorld <- borders('world', colour = 'white', fill = 'white')
     mp <- ggplot() + mapWorld + theme(panel.background = element_rect(fill = 'lightblue'))

But, I still get the error  <Error in x[[1]] : subscript out of bounds> when trying to run ENMeval...

**Comment by BrunoVilela** [comment]
I mean not that the buffer desapear, but the map boundaries could increase... I still get the error when trying ENMeval too...

**Comment by ndimhypervol** [comment]
Yep, after refreshing my env I did get that plotting error -- thanks for the fix. I'll take a look at why ENMeval might be messing up.

**Comment by mlammens** [comment]
I think the ENMeval problem might be related to the predictor variables. The worldclim directory that is on @ndimhypervol system is not in the repo here, so there are actually no predictor variables loading up.

**Comment by mlammens** [comment]
Might be able to get around the worldclim issues with package dismo's `getData` function. I'll investigate.

**Comment by ndimhypervol** [comment]
Yes, I originally used getData(), but figured that we would just upload all the rasters to the server. Do we think that's not possible?

**Comment by mlammens** [comment]
@ndimhypervol I closed this issue and opened a new on to deal with only the getData issue. Let's move further discussion there.
